# Gridded_Data
[Link](https://www.youtube.com/watch?v=uCRkFwQqdJo&list=PLG19vXLQHvSAufDFgZEFAYQEwMJXklnQV&index=3)

In [1]:
import os                                     # operation system
import numpy as np                            # arrays and matrix math
import matplotlib.pyplot as plt               # plotting
from scipy import stats                       # summary statistics

In [2]:
os.chdir('workspace')                         # set working directory

## Load Binary Data to An NDARRAY

In [3]:
porosity_1d_array = np.fromfile('porosity_truth_map.dat')  

In [4]:
porosity_1d_array[0:10]

array([ 9.47058121,  9.91782937,  9.9798204 ,  9.91630812, 10.69861209,
       10.56588283, 11.83384658, 12.95500949, 13.26534495, 13.47717932])

## Preview NDARRAY

In [5]:
np.set_printoptions(precision=3, threshold=1.0e10)
porosity_1d_array[0:10]

array([ 9.471,  9.918,  9.98 ,  9.916, 10.699, 10.566, 11.834, 12.955,
       13.265, 13.477])

In [6]:
np.set_printoptions(precision=3, threshold=100)
porosity_1d_array[0:10]

array([ 9.471,  9.918,  9.98 ,  9.916, 10.699, 10.566, 11.834, 12.955,
       13.265, 13.477])

In [7]:
porosity_1d_array.shape

(10000,)

## Reshape NDARRAY

In [8]:
porosity_map = np.reshape(porosity_1d_array,(100,100))          # reshape the array to 100 x 100
print(porosity_map.shape)
ny = porosity_map.shape[0]
nx = porosity_map.shape[1]
print(nx, ny)

(100, 100)
100 100


## Flatten NDARRAY

In [9]:
flatten_porosity_map = porosity_map.flatten()   # flatten 2D map
print(flatten_porosity_map)
flatten_porosity_map.shape

[ 9.471  9.918  9.98  ... 10.763 10.309 10.866]


(10000,)

## Read and write binary files

In [10]:
porosity_map.tofile('porosity_test.dat')                                    # save 2D array to 1D binary file
porosity_test = np.fromfile('porosity_test.dat')                            # read the 1D array back to 1D array
check = np.array_equal(porosity_map, np.reshape(porosity_test, (100,100)))  # check if loaded = saved
print(check)

True


## Write ASCII comma delimited files

In [11]:
np.savetxt('porosity_map.csv', porosity_map, delimiter=',')   # save 2D array to 2D columns delimited

## Read ASCII comma delimited files

In [19]:
porosity_map_test = np.loadtxt('porosity_map.csv', delimiter=',')
test = np.array_equal(porosity_map, porosity_map_test)
print(f'Is the array we wrote out and read back in the same as the original array? {test}.')
print(f'The loaded array has a shape {porosity_map_test.shape}.')

Is the array we wrote out and read back in the same as the original array? True.
The loaded array has a shape (100, 100).


## Read and Write GEO-EAS files

In [23]:
import geostatspy.GSLIB as GSLIB
GSLIB.ndarray2GSLIB(porosity_map, "porosity_mapGSLIB.out", 'porosity') # save the gribbed data to Geo-EAS format
porosity_map_test2, col_name = GSLIB.GSLIB2ndarray('porosity_map_GSLIB.out', 0, nx, ny)
test = np.array_equal(porosity_map.porosity_map_test2)
print(f'The ndarray from the file we read is the same as before we saved it, {test}')

FileNotFoundError: [Errno 2] No such file or directory: 'porosity_map_GSLIB.out'