# Gridded_Data
[Link](https://www.youtube.com/watch?v=uCRkFwQqdJo&list=PLG19vXLQHvSAufDFgZEFAYQEwMJXklnQV&index=3)

In [1]:
import os                                     # operation system
import numpy as np                            # arrays and matrix math
import matplotlib.pyplot as plt               # plotting
from scipy import stats                       # summary statistics

In [2]:
os.chdir('workspace')                         # set working directory

## Load Binary Data to An NDARRAY

In [3]:
porosity_1d_array = np.fromfile('porosity_truth_map.dat')  

In [4]:
porosity_1d_array[0:10]

array([ 9.47058121,  9.91782937,  9.9798204 ,  9.91630812, 10.69861209,
       10.56588283, 11.83384658, 12.95500949, 13.26534495, 13.47717932])

## Preview NDARRAY

In [5]:
np.set_printoptions(precision=3, threshold=1.0e10)
porosity_1d_array[0:10]

array([ 9.471,  9.918,  9.98 ,  9.916, 10.699, 10.566, 11.834, 12.955,
       13.265, 13.477])

In [7]:
np.set_printoptions(precision=3, threshold=100)
porosity_1d_array[0:10]

array([ 9.471,  9.918,  9.98 ,  9.916, 10.699, 10.566, 11.834, 12.955,
       13.265, 13.477])

In [8]:
porosity_1d_array.shape

(10000,)

## Reshape NDARRAY

In [9]:
porosity_map = np.reshape(porosity_1d_array,(100,100))          # reshape the array to 100 x 100
print(porosity_map.shape)
ny = porosity_map.shape[0]
nx = porosity_map.shape[1]
print(nx, ny)

(100, 100)
100 100


## Flatten NDARRAY

In [11]:
flatten_porosity_map = porosity_map.flatten()   # flatten 2D map
print(flatten_porosity_map)
flatten_porosity_map.shape

[ 9.471  9.918  9.98  ... 10.763 10.309 10.866]


(10000,)

## Read and write binary files

In [12]:
porosity_map.tofile('porosity_test.dat')                                    # save 2D array to 1D bin
porosity_test = np.fromfile('porosity_test.dat')                            # read the 1D array back to 1D array
check = np.array_equal(porosity_map, np.reshape(porosity_test, (100,100)))  # check if loaded = saved
print(check)

True
